Repository pnu-oslab-org/Code-Test, pull requests merged in 2021-04, with the labels that each got.

#3 [10165] 버스 노선
  8주차/10165.cpp
  8주차/18809.cpp
Labels: 그리디 알고리즘, 정렬

#1 [18809] Gaaaaaarden
  8주차/10165.cpp
Labels: 구현, 그래프 이론, 그래프 탐색, 너비 우선 탐색, 브루트포스 알고리즘, 시뮬레이션

#4 [1854] K번째 최단경로 찾기
  10주차/1976.cpp
  8주차/1854.cpp
  9주차/10875.cpp
Labels: 그래프 이론, 다익스트라

#2 [16000] 섬
  8주차/16000.cpp
  9주차/2191.cpp
Labels: 그래프 이론, 그래프 탐색, 단절점과 단절선
